### ISSUE TITLE
Doesn't compile with gcc 10

### ISSUE THREAD

**Issue by Tokariew** [draconisPW/PWMAngband#287]
I was able to compile f4859c4
but today when pull commits i got ld errors…

```
Successfully compiled common/z-virt.c.
/usr/bin/ld: common/z-type.o:/home/tokariew/gits/others/PWMAngband/src/common/z-type.c:28: multiple definition of `ANGBAND_SYS'; client/ui-init.o:/home/tokariew/gits/others/PWMAngband/src/client/ui-init.c:61: first defined here
/usr/bin/ld: common/z-type.o:/home/tokariew/gits/others/PWMAngband/src/common/z-type.c:35: multiple definition of `ANGBAND_DIR_CUSTOMIZE'; client/ui-init.o:/home/tokariew/gits/others/PWMAngband/src/client/ui-init.c:66: first defined here
/usr/bin/ld: common/z-type.o:/home/tokariew/gits/others/PWMAngband/src/common/z-type.c:37: multiple definition of `ANGBAND_DIR_SCREENS'; client/ui-init.o:/home/tokariew/gits/others/PWMAngband/src/client/ui-init.c:67: first defined here
/usr/bin/ld: common/z-type.o:/home/tokariew/gits/others/PWMAngband/src/common/z-type.c:38: multiple definition of `ANGBAND_DIR_FONTS'; client/ui-init.o:/home/tokariew/gits/others/PWMAngband/src/client/ui-init.c:68: first defined here
/usr/bin/ld: common/z-type.o:/home/tokariew/gits/others/PWMAngband/src/common/z-type.c:39: multiple definition of `ANGBAND_DIR_TILES'; client/ui-init.o:/home/tokariew/gits/others/PWMAngband/src/client/ui-init.c:69: first defined here
/usr/bin/ld: common/z-type.o:/home/tokariew/gits/others/PWMAngband/src/common/z-type.c:40: multiple definition of `ANGBAND_DIR_SOUNDS'; client/ui-init.o:/home/tokariew/gits/others/PWMAngband/src/client/ui-init.c:70: first defined here
/usr/bin/ld: common/z-type.o:/home/tokariew/gits/others/PWMAngband/src/common/z-type.c:41: multiple definition of `ANGBAND_DIR_ICONS'; client/ui-init.o:/home/tokariew/gits/others/PWMAngband/src/client/ui-init.c:71: first defined here
/usr/bin/ld: common/z-type.o:/home/tokariew/gits/others/PWMAngband/src/common/z-type.c:42: multiple definition of `ANGBAND_DIR_USER'; client/ui-init.o:/home/tokariew/gits/others/PWMAngband/src/client/ui-init.c:72: first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:47: pwmangclient.o] Error 1
make[3]: Leaving directory '/home/tokariew/gits/others/PWMAngband/src'
make[2]: *** [../mk/buildsys.mk:112: all] Error 2
make[2]: Leaving directory '/home/tokariew/gits/others/PWMAngband/src'
make[1]: *** [mk/buildsys.mk:115: subdirs] Error 2
make[1]: Leaving directory '/home/tokariew/gits/others/PWMAngband'
make: *** [mk/buildsys.mk:110: all] Error 2
```

**Comment by s88100** [comment]
which linux distribution? compilation works on Debian 10

**Comment by Tokariew** [comment]
fedora 32/33 with gcc 10.2.1

**Comment by draconisPW** [comment]
The ANGBAND_XXX have been redefined in commit ea5bd83, so yeah expect such errors. It shouldn't compile if PRIVATE_USER_PATH is defined. No idea why this part of code that redefines those variable is there, doesn't make much sense.

**Comment by Tokariew** [comment]
It compile fine with gcc-9.3 on fedora 31, so error is probably with newer gcc

**Comment by draconisPW** [comment]
My bet is that gcc 9 treats "multiple definition of symbol XXX" as a warning while newer gcc treats that as an error. A simple workaround is to use compile option to treat it as a warning with newer gcc, or I could simply amend the code to remove the duplicate definitions.

**Comment by Tokariew** [comment]
adding -fcommon flag to cflags work.
https://gcc.gnu.org/gcc-10/porting_to.html 
Adding extern before variables from error msg to client/ui-init.c don't fix completly still one error here:
```
Successfully compiled common/z-virt.c.
/usr/bin/ld: common/z-type.o:/home/tokariew/gits/others/PWMAngband/src/common/z-type.c:28: multiple definition of `ANGBAND_SYS'; client/ui-init.o:/home/tokariew/gits/others/PWMAngband/src/client/ui-init.c:61: first defined here
collect2: error: ld returned 1 exit status
```

**Comment by draconisPW** [comment]
I've removed the duplicate definitions, code should use the ones in z-type.c.
